### ISSUE TITLE
Consolidate into 1 repo

### ISSUE THREAD

**Issue by timkpaine** [conda-forge/python-cufflinks-feedstock#6]
https://github.com/santosjorge/cufflinks/issues/226
https://github.com/conda-forge/cufflinks-py-feedstock/issues/9

**Comment by dhirschfeld** [comment]
Hi @timkpaine 
PR #5 in this repo builds both `python-cufflinks` and `cufflinks-py` from a single source which I think is a better way to resolve the duplicate package issue than separately maintaining 2 repos.

Would you be happy to archive the [`cufflinks-py`](https://github.com/conda-forge/cufflinks-py-feedstock) feedstock and maintain both packages here?

If not, I'm happy to revert the building of the `cufflinks-py` meta-package here but we'd still need to address the current [naming problem](https://github.com/conda-forge/cufflinks-py-feedstock/pull/13#issuecomment-567771200) in `cufflinks-py`

**Comment by timkpaine** [comment]
Yep no problem

**Comment by dhirschfeld** [comment]
This is now done. I'll close this issue https://github.com/conda-forge/cufflinks-py-feedstock is archived...

**Comment by dhirschfeld** [comment]
`cufflinks-py` is now archived & this is now the official `cufflinks` `conda-forge` feedstock!
